# Generated by Django 5.1.6 on 2026-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Boş'), ('OCCUPIED', 'Dolu'), ('RESERVED', 'Rezerve'), ('OUT_OF_SERVICE', 'Servis dışı')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
